### ISSUE TITLE
Interested in merge of fork?

### ISSUE THREAD

**Issue by rivy** [u-tools/msls#1]
I've been maintaining a personal fork of your `msls` for the last few years on a private repo. As I see you've opened a repo here on github, I was wondering if you'd like to merge any of the code I've added.

The fork that I've constructed builds cleanly and easily on VC6/1200 through the most current version (I've specifically tested VC6/1200, VC8/1400, VC11/1700, VC2017/1914). It's constructed in what I would call a  "contributor-friendly" manner with an easy, portable build process. The build process uses some BAT and makefile magic to determine (or find) the dev's current `cl` and tailor the build based on `cl` version without intervention. Although, to be fair, as this is the first time I've released it publicly, it's still at the "works-on-my-machine" level of reliability.

I've just finished merging your most recent commits into my repo and I've moved a copy of it here to github ([rivy/msls](https://github.com/rivy/msls)).

Let me know if you're interested in any of the code. And I'm happy to take feedback as well.

**Comment by aklietz** [comment]
Sounds great.  I'm new to github so please tell me how you'd like me to do it for you.  (I assume it is some combo of git pull / merge / push?)

-Alan Klietz (msls at u-tools dot c0m)

**Comment by rivy** [comment]
Since my repository was originally constructed from source tarballs, we don't have a common ancestor for PRs. I did merge your project repository into mine, but GitHub doesn't see that as enough to put us into the same "network". I may have to rebase off of a baseline fork of your repository to allow the usual PR methodology on GitHub.

I'll look into it.

In the meanwhile, clone it and take a look at it. I've made quite a few organizational changes that made sense to me, but might not be what you want. If it's still of interest, I'll see about working out some way to relate the repositories so that usual PRs will work.

**Comment by rivy** [comment]
@aklietz , 

I've figured out how to link the repos as forks of each other and just completed the link. If you decide you want to pull in the changes, I'll be happy to help. If you'll let me know beforehand, I'll spend some time rewriting the history so that the source tarballs commits are revised to be under your name. Right now, it looks like I wrote most of the code in the repo, whereas it was mostly reorg, a few bug fixes, and a new build process.

**Comment by aklietz** [comment]
I'll probably just integrate your stuff manually into the main branch and tag it (still learning git). 

I'm looking over your changes now. I'm not sure what the /* ==<ff>== */ comments are for. Some of the #pragmas need to be fixed up to compile on other Visual Studio versions.  The insertion of digital signatures (Microsoft Authenticode) need to be integrated into the build process for the public EXE. I also need to re-think a few other things about the build process (for example, building on VS2017 using standalone ucrt and libc). Thanks, -Alan

**Comment by rivy** [comment]
The /* == <ff> === */ comments were replacements for literal formfeeds embedded in the source code files. I wan't sure what the utility of the formfeeds actually was, so I just replaced them each with a comment flagging their location. I would just as soon remove them.

I'm not sure about the pragmas. What warning level are you using? I compiled the code warning-free for VC6 throught the most recent VC2017, using the standard warning level. I can look into making it compile warning-free at a different warning level if you'd like...

**Comment by rivy** [comment]
I also added a minimal AppVeyor CI configuration and a couple of useful dev scripts that I've written to the [`dev` branch](https://github.com/rivy/msls/tree/dev).

The AppVeyor config currently just tests for successful compilation on several VC versions, and enforces whitespace style.

**Comment by aklietz** [comment]
I folded in your build process and fixes (thank you!)  Tagged as msls v4.8.328

**Comment by rivy** [comment]
I quite glad you've taken the time to publish your repository in public. And I'm glad you could use some of the patches that I've cobbled together over the last few years.

I have two comments:

### 1

I would remove and avoid the `* text=auto` line in '.gitattributes' ... IMHO, it'll lead to future heartburn.

see https://stackoverflow.com/questions/20168639/git-commit-get-fatal-error-fatal-crlf-would-be-replaced-by-lf-in

see https://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git/2825829#2825829

Almost all editors now can handle either LF or CRLF line endings. So, you generally don't need to worry about being able to edit the files. But line ending changes can lead to huge change lists for commits, obscuring the actual important modifications in a sea of line changes, differing only by EOL. And, generally, most repositories use LFs. So, personally, I've standardized on LFs, only using CRLFs for specific files that must have them (so far, that's only BAT and CMD files).

My process is that I will place an .editorconfig style file in the repository root directory as a gentle suggestion for the correct line endings for contributors. Additionally, I usually implement a style test that fails if files are submitted with the wrong EOL format. The style test I'm using checks for whitespace issues beyond just EOLs (including leading TABs, trailing whitespace, ...), any of which can lead to change sets which are "semi-invisible".

You can see my testing setup (dbin/... and the AppVeyor CI config (.appveyor.yml)) in the '[dev](https://github.com/rivy/msls/tree/dev)' branch of my fork).

I'm happy to create a pull request so that you can add them. And, I can also guide you in setting up AppVeyor for automated testing for each push to your repository.

### 2

I did see that you gave me a credit by-line in the build files and the original patching commit. And it is appreciated. But, when you pull in work from other folks manually, I would recommend that you give them co-author credit in the commit message so they are seen by `git` and host tooling as contributors.

see https://blog.github.com/2018-01-29-commit-together-with-co-authors

I use git-mob ( see https://tech.findmypast.com/co-author-commits-with-git-mob ).

In this case, to add me as a co-author for the merge/re-org commits, you'll need to rebase the commits and push them back up to github. The process is:

  - `git checkout master`
  - at this point, you can optionally add a bookmark with `git branch bookmark` as a safety precaution
  - next, `git rebase -i 88d2a9e` or `github rebase -i v4.7.321`
    - 'reword' the commit messages for commits 9ad9fdb and 0b5bdb2
    - adding two blank lines followed by `Co-authored-by: Roy Ivy III <rivy.dev@gmail.com>` to each commit
  - finally, make sure that you're happy with the log and `git push -f` to push the changes back up to master; you'll then see both of our names/icons in the respective commits

That way I'll get a co-author credit for the changes. Not a big deal, but I'd appreciate the co-author-ship nod.

**Comment by aklietz** [comment]
I fixed the log messages for you. I hope I did it right.

I have some scripts that assume crlf. The choice of lf versus crlf is purely a local preference.  Git stores all text files in the repository with lf regardless.  I agree that autocrlf should not be forced so I took it out of .gitattributes.   That should make our both our respective scripts happy :-).    Thanks again, -Alan

**Comment by rivy** [comment]
👍 
Looks great! Thanks for the nod.
😄 
I hope the new build process helps. It's made it a lot easier for me.
If you decide to add AppVeyor testing, let me know. I'm happy to help you put something together.
